<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="50" started-at="2015-07-13T12:02:24Z" finished-at="2015-07-13T12:02:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="50" started-at="2015-07-13T12:02:24Z" finished-at="2015-07-13T12:02:24Z">
      <class name="com.comarch.training.PositiveCases">
        <test-method status="PASS" signature="init()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="init" is-config="true" duration-ms="20" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="AddingTest()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="AddingTest" duration-ms="0" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddingTest -->
        <test-method status="PASS" signature="AddingToMemory()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="AddingToMemory" duration-ms="0" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddingToMemory -->
        <test-method status="PASS" signature="MultiplyTest()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="MultiplyTest" duration-ms="0" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MultiplyTest -->
        <test-method status="FAIL" signature="divideTest()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="divideTest" duration-ms="0" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2.0] but found [2.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2.0] but found [2.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:167)
	at com.comarch.training.PositiveCases.divideTest(PositiveCases.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divideTest -->
        <test-method status="PASS" signature="MinusTest()[pri:0, instance:com.comarch.training.PositiveCases@71c7db30]" name="MinusTest" duration-ms="0" started-at="2015-07-13T14:02:24Z" finished-at="2015-07-13T14:02:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MinusTest -->
      </class> <!-- com.comarch.training.PositiveCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
